version: "3.8"

services:
  samba:
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile
    container_name: samba-alpine
    ports:
      - "445:445"
    environment:
      - SAMBA_USER=${SAMBA_USER}
      - SAMBA_PASSWORD=${SAMBA_PASSWORD}
      - SAMBA_GROUP=${SAMBA_GROUP}
      - SAMBA_UID=${SAMBA_UID}
      - SAMBA_GID=${SAMBA_GID}
    volumes:
      - ./data:/srv/samba
      - ./config:/etc/samba:ro
    restart: unless-stopped

