[global]
   workgroup = WORKGROUP
   server string = "The best of the best of the best samba server"
   map to guest = Never
   log file = /var/log/samba/%m.log
   max log size = 1000
   load printers = no
   printing = bsd
   disable spoolss = yes
   interfaces = 127.0.0.1 192.168.0.0/24
   bind interfaces only = no

   security = user
   passdb backend = tdbsam
   obey pam restrictions = no
   unix password sync = no

[public]
   path = /srv/samba/public
   browsable = yes
   guest ok = yes
   read only = no
   create mask = 0777
   directory mask = 0777
   force user = nobody

[group_share]
   comment = Group share
   path = /srv/samba/private/%G
   browsable = yes
   guest ok = no
   read only = no
   valid users = @%G
   write list = @%G
   create mask = 0660
   directory mask = 2770
   force group = %G

[user_share]
   comment = Private user share
   path = /srv/samba/private/%U
   browsable = no
   guest ok = no
   read only = no
   valid users = %U
   create mask = 0600
   directory mask = 0700

