#!/usr/bin/bash

# Maintainer: Ren Ellyhcnium <centipede@internet.ru>

# base launch

LOG_FILE=/var/log/samba-launcher.log

set -euo pipefail
mkdir -p /var/log
touch $LOG_FILE
chown root:root "$LOG_FILE"
chmod 640 "$LOG_FILE"
exec >> $LOG_FILE 2>&1

is_root(){
	[ "$(id -u)" -eq 0 ]
}

if ! is_root; then
	echo "[ EE ] UUID is not 0, launch script from root"
	exit 1
fi

if command -v dnf >/dev/null 2>&1; then
	TARGET_DISTRO=rh
elif command -v apk >/dev/null 2>&1; then
	TARGET_DISTRO=alpine
else
	echo "[ EE ] Unknown package manager, not supported distro"
	exit 1
fi

if [[ $TARGET_DISTRO = rh ]]; then
	dnf -y upgrade
	if ! command -v smbd >/dev/null 2>&1; then
		dnf -y install samba
	fi

	systemctl enable --now smb --no-block || {
		echo "[ EE ] Unable to launch smbd"
		exit 1
}
elif [[ $TARGET_DISTRO = alpine ]]; then
	apk update
	apk upgrade
	if ! command -v smbd >/dev/null 2>&1; then
		apk add samba
	fi

	rc-update add samba default
	rc-service samba start || {
		echo "[ EE ] Unable to launch smbd"
		exit 1
	}
fi

echo "[ II ] smbd successfuly launched"

# firewall

IPTABLES_SAVE_FILE=/etc/iptables.rules

if command -v iptables >/dev/null 2>&1; then
	if iptables -L INPUT -n | grep -q ACCEPT; then
		echo "[ II ] iptables was detected as firewall"
		for proto in "tcp" "udp"; do
			for port in "137" "138" "139"; do
				if iptables -C INPUT -p $proto --dport $port -j ACCEPT >/dev/null 2>&1; then
					echo "[ II ] rule for $proto:$port exist"
				else
					echo "[ II ] adding rule for $proto:$port"
					iptables -I INPUT -p $proto --dport $port -m comment --comment "samba" -j ACCEPT
				fi
			done
		done
		if iptables -C INPUT -p tcp --dport 445 -j ACCEPT >/dev/null 2>&1; then
			echo '[ II ] rule for tcp:445 exist'
		else
			echo '[ II ] adding rule for tcp:445'
			iptables -I INPUT -p tcp --dport 445 -m comment --comment "samba" -j ACCEPT
		fi

	else
		echo "[ II ] iptables exists, but inactive, skipped"
 	fi
fi
if command -v ufw >/dev/null 2>&1; then
	if ufw status verbose | grep -qi inactive; then
		echo '[ II ] ufw exists, but inactive, skipped'
	else
		echo '[ II ] ufw was detected as firewall'
	fi		
fi
if command -v firewall-cmd >/dev/null 2>&1; then
	if systemctl is-active --quiet firewalld; then
		echo '[ II ] firewalld was detected as firewall'
	else
		echo '[ II ] firewalld exists, but inactive, skipped'
	fi
fi
